### ISSUE TITLE
How to use nodebb-plugin-knowledge-base?

### ISSUE THREAD

**Issue by ink-blot** [julianlam/nodebb-plugin-knowledge-base#3]
Hello. I was wondering if you could provide some very brief instructions on how to use the nodebb-knowlege-base plugin? It looks useful but unfortunately the readme is very brief. What are settings 1 and 2 for in the ACP?

**Comment by julianlam** [comment]
Ah, you can ignore the setting page, that should be removed.

This plugin exposes a new category privilege under "Manage -> Privileges". When checked, it allows users and groups to collaboratively edit topics.

**Comment by julianlam** [comment]
v1.0.3
