### ISSUE TITLE
selecting a previous edit / viewing the contributor

### ISSUE THREAD

**Issue by AliCihan** [julianlam/nodebb-plugin-knowledge-base#5]
Hi @julianlam , 

We can see previous edits, however when there is a mistake can we go back to a previous version? Currently, we can just view the previous versions but cannot select to go back to that version. 

Additionally, it would be great to see who made the edits... Currently, we can only see the last person who edited it... 

( By the way, you wrote before but just to remind again clicking the Knowledge Base in ACP crashes NodeBB, FYI... I know that setting is not necessary)

Thanks...

**Comment by AliCihan** [comment]
I think this commit solves most of the problem I mentioned: 
https://github.com/NodeBB/NodeBB/issues/8406

However, it would also be great to see "contributor / admin / moderator" that made the edit... 

Thanks.

**Comment by julianlam** [comment]
You can see the username of the person who made that particular edit.

**Comment by AliCihan** [comment]
@julianlam where should I look? Can you direct me, please? 
In our case, the username is not written anywhere on the post, only the last person that made the edit is visible... 

![Screen Shot 2020-06-22 at 3 40 21 PM](https://user-images.githubusercontent.com/52054408/85328739-3e862580-b49f-11ea-84cf-08365a074089.png)
![Screen Shot 2020-06-22 at 3 42 49 PM](https://user-images.githubusercontent.com/52054408/85328741-3e862580-b49f-11ea-818b-3b0c23ec4b1c.png)

**Comment by julianlam** [comment]
It might be only released in v1.14, or latest master :smile: 

I made the changes to the theme late, but they should be in latest persona now.
